Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.define "kontrolplane1" do |kontrolplane1|
    kontrolplane1.vm.hostname = "kontrolplane1"
    kontrolplane1.vm.network "private_network", :ip => "10.0.0.11"
    kontrolplane1.vm.provision "shell", path: "k8s_kontrolplane.sh"
    kontrolplane1.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
  end

  (2..3).each do |kompute_host_cpt|
		config.vm.define "kompute#{kompute_host_cpt}" do |host_config|
			host_config.vm.hostname = "kompute#{kompute_host_cpt}"
			host_config.vm.network "private_network", :ip => "10.0.0.1#{kompute_host_cpt}"
      host_config.vm.provision "shell", path: "k8s_kompute.sh"
			host_config.vm.provider "libvirt" do |hv|
				hv.cpus = 2
				hv.memory = 2048
			end
    end
	end
end
