Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.define "k1" do |k1|
    k1.vm.hostname = "k1"
    k1.vm.network "private_network", :ip => "10.0.0.11"
    k1.vm.provision "shell", path: "k8s_controlpane.sh"
    k1.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end
  end

  (2..3).each do |k_host_cpt|
		config.vm.define "k#{k_host_cpt}" do |host_config|
			host_config.vm.hostname = "k#{k_host_cpt}"
			host_config.vm.network "private_network", :ip => "10.0.0.1#{k_host_cpt}"
      host_config.vm.provision "shell", path: "k8s_compute.sh"
			host_config.vm.provider "libvirt" do |hv|
				hv.cpus = 2
				hv.memory = 2048
			end
    end
	end

  # config.vm.define "k2" do |k2|
  #   k2.vm.hostname = "k2"
  #   k2.vm.provision "shell", path: "k8s_compute.sh"
  #   k2.vm.provider :libvirt do |domain|
  #     domain.memory = 2048
  #     domain.cpus = 2
  #   end
  # end
  #
  # config.vm.define "k3" do |k3|
  #   k3.vm.hostname = "k3"
  #   k3.vm.provision "shell", path: "k8s_compute.sh"
  #   k3.vm.provider :libvirt do |domain|
  #     domain.memory = 2048
  #     domain.cpus = 2
  #   end
  # end

end
